version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: crud_mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    restart: always
    ports:
      - "3306:3306"
    networks:
      - dev_network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: crud_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "1234"
    networks:
      - dev_network

networks:
  dev_network:

volumes:
  db_data:
